version: '3.1'
services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  wordpress:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: segment-cache-for-wp-engine
    restart: always
    depends_on:
      - db
    links:
      - db:mysql
    volumes:
      - ../:/workspace
      - ../:/var/www/html/wp-content/plugins/segment-cache-for-wp-engine
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
